app:
  security:
    oauth2:
      client:
        clientId: testApp
        clientSecret: testApp
        callbackUrl: http://127.0.0.1:9010/api/oauth/callback
        scopes:
          - offline_access
          - ui_access

spring:
  sleuth:
    otel:
      config:
        custom-span-name: true
        trace-id-ratio-based: 1
      exporter:
        otlp:
          endpoint: http://otel-collector:4317
    propagation:
      type: W3C

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus