apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/name: grafana
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 3000
