service:
  port: 8080
  tracing:
    otelEndpoint: ${OTEL_ENDPOINT}

security:
  oauth2:
    resource:
      issuer: ${OAUTH_ISSUER}
      audiences:
        - app-web-client
        - backend
      jwkSetUrl: "${OAUTH_ISSUER}/protocol/openid-connect/certs"