service:
  port: 8080
  tracing:
    otelEndpoint: http://otel-collector:4317


security:
  oauth2:
    resource:
      issuer: "http://keycloak:8080"
      audiences:
        - app-web-client
        - backend
      jwkSetUrl: "http://keycloak:8080/oauth2/jwks"