server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${OAUTH_ISSUER}/protocol/openid-connect/certs"
          audiences:
            - app-web-client
            - backend

  sleuth:
    otel:
      config:
        customSpanName: true
        trace-id-ratio-based: 1
      exporter:
        otlp:
          endpoint: ${OTEL_ENDPOINT}
    propagation:
      type: W3C

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus