apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  rules:
    - host: {{ .Values.global.hostname }}
      http:
        paths:
          - path: /api/{{ .Chart.Name }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.targetPort }}