apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-secret.name" .}}
type: Opaque
data:
  OAUTH_CLIENT_ID: {{ .Values.global.oauth.client.id| b64enc }}
  OAUTH_CLIENT_SECRET: {{ .Values.global.oauth.client.secret| b64enc }}