apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-config.name" .}}
data:
  OTEL_ENDPOINT:  http://tempo.monitoring:4317
  APP_MAIN_DOMAIN: http://{{.Values.global.hostname}}
  OAUTH_ISSUER: https://auth.mlevsh.in/realms/project-base