apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-pg-pvc
spec:
  storageClassName: {{.Values.storage.className}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.size}}