apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-pg.secret-name" . }}
type: Opaque
data:
  username: {{ "keycloak" | b64enc }}
  password: {{  randAlphaNum 32 | b64enc }}
  database: {{ "keycloak" | b64enc }}