apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-pg-service
  labels:
    app: {{.Release.Name}}-pg
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: {{.Release.Name}}-pg