apiVersion: v1
kind: Secret
metadata:
  name: {{ include "token-handler-service-secret.name" .}}
data:
  SECURITY_SESSION_ENCRYPTION_KEY: {{ randNumeric 32 | b64enc }}
  SECURITY_SESSION_SIGN_KEY: {{ randNumeric 32 | b64enc }}