spring:
  application:
    name: spring-test-service

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1
      exporter:
        otlp:
          endpoint: http://otel-collector:4317
    propagation:
      type: W3C

server:
  port: 9090