service:
  port: 8010
  tracing:
    otelEndpoint: http://localhost:60658


security:
  oauth2:
    resource:
      issuer: "http://127.0.0.1:9000"
      audience: test
      realm: test
      jwkSetUrl: "http://127.0.0.1:9000/oauth2/jwks"