service:
  port: 8080
  tracing:
    otelEndpoint: http://tempo.monitoring:4317


security:
  oauth2:
    resource:
      issuer: "http://authorization-service:8080"
      audience: test
      realm: test
      jwkSetUrl: "http://authorization-service:8080/oauth2/jwks"